# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import usuarios_pb2 as usuarios__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuarios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/CrearUsuario',
                request_serializer=usuarios__pb2.CrearUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.CrearUsuarioResponse.FromString,
                _registered_method=True)
        self.ObtenerUsuarios = channel.unary_unary(
                '/usuarios.UsuarioService/ObtenerUsuarios',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=usuarios__pb2.ObtenerUsuariosResponse.FromString,
                _registered_method=True)
        self.ActualizarUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/ActualizarUsuario',
                request_serializer=usuarios__pb2.ActualizarUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.ActualizarUsuarioResponse.FromString,
                _registered_method=True)
        self.EliminarUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/EliminarUsuario',
                request_serializer=usuarios__pb2.EliminarUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.EliminarUsuarioResponse.FromString,
                _registered_method=True)


class UsuarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearUsuario,
                    request_deserializer=usuarios__pb2.CrearUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.CrearUsuarioResponse.SerializeToString,
            ),
            'ObtenerUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerUsuarios,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=usuarios__pb2.ObtenerUsuariosResponse.SerializeToString,
            ),
            'ActualizarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarUsuario,
                    request_deserializer=usuarios__pb2.ActualizarUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.ActualizarUsuarioResponse.SerializeToString,
            ),
            'EliminarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarUsuario,
                    request_deserializer=usuarios__pb2.EliminarUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.EliminarUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuarios.UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuarios.UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/CrearUsuario',
            usuarios__pb2.CrearUsuarioRequest.SerializeToString,
            usuarios__pb2.CrearUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/ObtenerUsuarios',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            usuarios__pb2.ObtenerUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/ActualizarUsuario',
            usuarios__pb2.ActualizarUsuarioRequest.SerializeToString,
            usuarios__pb2.ActualizarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/EliminarUsuario',
            usuarios__pb2.EliminarUsuarioRequest.SerializeToString,
            usuarios__pb2.EliminarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
