# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"4\n\x13\x43rearUsuarioRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"Z\n\x14\x43rearUsuarioResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\"\n\x07usuario\x18\x03 \x01(\x0b\x32\x11.usuarios.Usuario\">\n\x17ObtenerUsuariosResponse\x12#\n\x08usuarios\x18\x01 \x03(\x0b\x32\x11.usuarios.Usuario\"E\n\x18\x41\x63tualizarUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"_\n\x19\x41\x63tualizarUsuarioResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\"\n\x07usuario\x18\x03 \x01(\x0b\x32\x11.usuarios.Usuario\"$\n\x16\x45liminarUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"9\n\x17\x45liminarUsuarioResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\xe3\x02\n\x0eUsuarioService\x12M\n\x0c\x43rearUsuario\x12\x1d.usuarios.CrearUsuarioRequest\x1a\x1e.usuarios.CrearUsuarioResponse\x12L\n\x0fObtenerUsuarios\x12\x16.google.protobuf.Empty\x1a!.usuarios.ObtenerUsuariosResponse\x12\\\n\x11\x41\x63tualizarUsuario\x12\".usuarios.ActualizarUsuarioRequest\x1a#.usuarios.ActualizarUsuarioResponse\x12V\n\x0f\x45liminarUsuario\x12 .usuarios.EliminarUsuarioRequest\x1a!.usuarios.EliminarUsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=57
  _globals['_USUARIO']._serialized_end=109
  _globals['_CREARUSUARIOREQUEST']._serialized_start=111
  _globals['_CREARUSUARIOREQUEST']._serialized_end=163
  _globals['_CREARUSUARIORESPONSE']._serialized_start=165
  _globals['_CREARUSUARIORESPONSE']._serialized_end=255
  _globals['_OBTENERUSUARIOSRESPONSE']._serialized_start=257
  _globals['_OBTENERUSUARIOSRESPONSE']._serialized_end=319
  _globals['_ACTUALIZARUSUARIOREQUEST']._serialized_start=321
  _globals['_ACTUALIZARUSUARIOREQUEST']._serialized_end=390
  _globals['_ACTUALIZARUSUARIORESPONSE']._serialized_start=392
  _globals['_ACTUALIZARUSUARIORESPONSE']._serialized_end=487
  _globals['_ELIMINARUSUARIOREQUEST']._serialized_start=489
  _globals['_ELIMINARUSUARIOREQUEST']._serialized_end=525
  _globals['_ELIMINARUSUARIORESPONSE']._serialized_start=527
  _globals['_ELIMINARUSUARIORESPONSE']._serialized_end=584
  _globals['_USUARIOSERVICE']._serialized_start=587
  _globals['_USUARIOSERVICE']._serialized_end=942
# @@protoc_insertion_point(module_scope)
