# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cursos_pb2 as cursos__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cursos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CursoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertarCurso = channel.unary_unary(
                '/cursos.CursoService/InsertarCurso',
                request_serializer=cursos__pb2.InsertarCursoRequest.SerializeToString,
                response_deserializer=cursos__pb2.InsertarCursoResponse.FromString,
                _registered_method=True)
        self.ObtenerCursos = channel.unary_unary(
                '/cursos.CursoService/ObtenerCursos',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=cursos__pb2.ObtenerCursosResponse.FromString,
                _registered_method=True)
        self.ObtenerCurso = channel.unary_unary(
                '/cursos.CursoService/ObtenerCurso',
                request_serializer=cursos__pb2.ObtenerCursoRequest.SerializeToString,
                response_deserializer=cursos__pb2.ObtenerCursoResponse.FromString,
                _registered_method=True)
        self.ActualizarCurso = channel.unary_unary(
                '/cursos.CursoService/ActualizarCurso',
                request_serializer=cursos__pb2.ActualizarCursoRequest.SerializeToString,
                response_deserializer=cursos__pb2.ActualizarCursoResponse.FromString,
                _registered_method=True)
        self.EliminarCurso = channel.unary_unary(
                '/cursos.CursoService/EliminarCurso',
                request_serializer=cursos__pb2.EliminarCursoRequest.SerializeToString,
                response_deserializer=cursos__pb2.EliminarCursoResponse.FromString,
                _registered_method=True)


class CursoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertarCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCursos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CursoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertarCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertarCurso,
                    request_deserializer=cursos__pb2.InsertarCursoRequest.FromString,
                    response_serializer=cursos__pb2.InsertarCursoResponse.SerializeToString,
            ),
            'ObtenerCursos': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCursos,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=cursos__pb2.ObtenerCursosResponse.SerializeToString,
            ),
            'ObtenerCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCurso,
                    request_deserializer=cursos__pb2.ObtenerCursoRequest.FromString,
                    response_serializer=cursos__pb2.ObtenerCursoResponse.SerializeToString,
            ),
            'ActualizarCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarCurso,
                    request_deserializer=cursos__pb2.ActualizarCursoRequest.FromString,
                    response_serializer=cursos__pb2.ActualizarCursoResponse.SerializeToString,
            ),
            'EliminarCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarCurso,
                    request_deserializer=cursos__pb2.EliminarCursoRequest.FromString,
                    response_serializer=cursos__pb2.EliminarCursoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cursos.CursoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cursos.CursoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CursoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertarCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cursos.CursoService/InsertarCurso',
            cursos__pb2.InsertarCursoRequest.SerializeToString,
            cursos__pb2.InsertarCursoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCursos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cursos.CursoService/ObtenerCursos',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            cursos__pb2.ObtenerCursosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cursos.CursoService/ObtenerCurso',
            cursos__pb2.ObtenerCursoRequest.SerializeToString,
            cursos__pb2.ObtenerCursoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cursos.CursoService/ActualizarCurso',
            cursos__pb2.ActualizarCursoRequest.SerializeToString,
            cursos__pb2.ActualizarCursoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cursos.CursoService/EliminarCurso',
            cursos__pb2.EliminarCursoRequest.SerializeToString,
            cursos__pb2.EliminarCursoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
