# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inscripcion_pb2 as inscripcion__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inscripcion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InscripcionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InscribirUsuarioEnCurso = channel.unary_unary(
                '/inscripcion.InscripcionService/InscribirUsuarioEnCurso',
                request_serializer=inscripcion__pb2.InscribirUsuarioRequest.SerializeToString,
                response_deserializer=inscripcion__pb2.InscribirUsuarioResponse.FromString,
                _registered_method=True)
        self.ObtenerCursosPorUsuario = channel.unary_unary(
                '/inscripcion.InscripcionService/ObtenerCursosPorUsuario',
                request_serializer=inscripcion__pb2.ObtenerCursosPorUsuarioRequest.SerializeToString,
                response_deserializer=inscripcion__pb2.ObtenerCursosPorUsuarioResponse.FromString,
                _registered_method=True)


class InscripcionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InscribirUsuarioEnCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCursosPorUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InscripcionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InscribirUsuarioEnCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.InscribirUsuarioEnCurso,
                    request_deserializer=inscripcion__pb2.InscribirUsuarioRequest.FromString,
                    response_serializer=inscripcion__pb2.InscribirUsuarioResponse.SerializeToString,
            ),
            'ObtenerCursosPorUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCursosPorUsuario,
                    request_deserializer=inscripcion__pb2.ObtenerCursosPorUsuarioRequest.FromString,
                    response_serializer=inscripcion__pb2.ObtenerCursosPorUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inscripcion.InscripcionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inscripcion.InscripcionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InscripcionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InscribirUsuarioEnCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inscripcion.InscripcionService/InscribirUsuarioEnCurso',
            inscripcion__pb2.InscribirUsuarioRequest.SerializeToString,
            inscripcion__pb2.InscribirUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCursosPorUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inscripcion.InscripcionService/ObtenerCursosPorUsuario',
            inscripcion__pb2.ObtenerCursosPorUsuarioRequest.SerializeToString,
            inscripcion__pb2.ObtenerCursosPorUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
