# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inscripcion.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inscripcion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11inscripcion.proto\x12\x0binscripcion\"?\n\x17InscribirUsuarioRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63urso_id\x18\x02 \x01(\x05\":\n\x18InscribirUsuarioResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"4\n\x1eObtenerCursosPorUsuarioRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\x05\"D\n\x1fObtenerCursosPorUsuarioResponse\x12!\n\x05\x63urso\x18\x01 \x03(\x0b\x32\x12.inscripcion.Curso\"@\n\x05\x43urso\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0bnombreCurso\x18\x02 \x01(\t\x12\x16\n\x0enombreProfesor\x18\x03 \x01(\t2\xf2\x01\n\x12InscripcionService\x12\x66\n\x17InscribirUsuarioEnCurso\x12$.inscripcion.InscribirUsuarioRequest\x1a%.inscripcion.InscribirUsuarioResponse\x12t\n\x17ObtenerCursosPorUsuario\x12+.inscripcion.ObtenerCursosPorUsuarioRequest\x1a,.inscripcion.ObtenerCursosPorUsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inscripcion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSCRIBIRUSUARIOREQUEST']._serialized_start=34
  _globals['_INSCRIBIRUSUARIOREQUEST']._serialized_end=97
  _globals['_INSCRIBIRUSUARIORESPONSE']._serialized_start=99
  _globals['_INSCRIBIRUSUARIORESPONSE']._serialized_end=157
  _globals['_OBTENERCURSOSPORUSUARIOREQUEST']._serialized_start=159
  _globals['_OBTENERCURSOSPORUSUARIOREQUEST']._serialized_end=211
  _globals['_OBTENERCURSOSPORUSUARIORESPONSE']._serialized_start=213
  _globals['_OBTENERCURSOSPORUSUARIORESPONSE']._serialized_end=281
  _globals['_CURSO']._serialized_start=283
  _globals['_CURSO']._serialized_end=347
  _globals['_INSCRIPCIONSERVICE']._serialized_start=350
  _globals['_INSCRIPCIONSERVICE']._serialized_end=592
# @@protoc_insertion_point(module_scope)
